pipeline:
  name: malyadr-poc-ci-2
  identifier: malyadrpocci2
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Malyadrigitrepo
        build: <+input>
  stages:
    - stage:
        name: source
        identifier: source
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Malyadrigitrepo
                    build:
                      type: branch
                      spec:
                        branch: main
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Test
                  name: Test_1
                  identifier: Test_1
                  spec:
                    connectorRef: Malyadridocker
                    image: node:18
                    shell: Sh
                    command: |-
                      npm install
                      CI=true npm test -- --ci --coverage || true --testResultsProcessor=jest-junit --jest-junit-output=junit.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - junit.xml
                    intelligenceMode: true
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: Malyadridocker
                    image: node:18
                    shell: Sh
                    command: |-
                      npm install  
                      npm run build
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - junit.xml
    - stage:
        name: sonar
        identifier: sonar
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: <+secrets.getValue("sonar-token-malyadri")>
                      domain: https://mydomain2.mooo.com/sonarqube
                      ssl: true
                    tool:
                      project_key: harness-ci-malyadri
    - stage:
        name: docker build and push
        identifier: docker_build_and_push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Malyadridocker
                    repo: malyadr/poc-react
                    tags:
                      - latest
                    caching: true
                    dockerfile: ./Dockerfile
